name = "brigada-ouro"
pages_build_output_dir = "app/public"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install"

# Crie o banco com: wrangler d1 create brigada-ouro
# Depois copie o database_id abaixo
[[d1_databases]]
binding = "DB"
database_name = "brigada-ouro"
database_id = "397a7ca6-93fa-4f31-a609-1ff22f6d1231"
